# yaml-language-server: $schema=https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json

#radixconfig production
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oneseismic
spec:
  environments:
    # stable production branch users are supposed to use
    - name: prod
      build:
        from: radix
    # small resources environment
    - name: test
      build:
        from: radix_test
    # environment that can be used for performance testing
    # environment must be stopped when not needed
    - name: test-large
      build:
        from: radix_test_large
  components:
    - name: server
      dockerfileName: Dockerfile
      ports:
        - name: http
          port: 8080
        - name: metrics
          port: 8081
      publicPort: http
      monitoringConfig:
        portName: metrics
      identity:
        azure:
          clientId: fd162526-89a0-448a-979f-655c0717db52
      environmentConfig:
        - environment: prod
          variables:
            ONESEISMIC_API_PORT: "8080"
            ONESEISMIC_API_CACHE_SIZE: "512" # MB
            ONESEISMIC_API_METRICS: "true"
            ONESEISMIC_API_METRICS_PORT: "8081"
            ONESEISMIC_API_TRUSTED_PROXIES: ""
            ONESEISMIC_API_BLOCKED_IPS: ""
            ONESEISMIC_API_BLOCKED_USER_AGENTS: ""
            OPENVDS_AZURE_IOMANAGER_THREAD_COUNT: ""
          secretRefs:
            azureKeyVaults:
              - name: S067-RadixKeyvault
                useAzureIdentity: true
                items:
                  - name: prod-allowlist
                    envVar: ONESEISMIC_API_STORAGE_ACCOUNTS
          monitoring: true
          resources:
            requests:
              memory: "8192Mi"
              cpu: "2000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
        - environment: test
          variables:
            ONESEISMIC_API_PORT: "8080"
            ONESEISMIC_API_CACHE_SIZE: "128" # MB
            ONESEISMIC_API_METRICS: "false"
            ONESEISMIC_API_METRICS_PORT: "8081"
            ONESEISMIC_API_TRUSTED_PROXIES: ""
            ONESEISMIC_API_BLOCKED_IPS: ""
            ONESEISMIC_API_BLOCKED_USER_AGENTS: ""
            OPENVDS_AZURE_IOMANAGER_THREAD_COUNT: ""
          secretRefs:
            azureKeyVaults:
              - name: S067-RadixKeyvault
                useAzureIdentity: true
                items:
                  - name: test-allowlist
                    envVar: ONESEISMIC_API_STORAGE_ACCOUNTS
          monitoring: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
          horizontalScaling:
            minReplicas: 0
            maxReplicas: 1
            triggers:
            - name: cron
              cron:
                timezone: Europe/Oslo
                start: 0 7 * * 1-5 # 07:00 Monday - Friday
                end: 0 21 * * 1-5 # 21:00 Monday - Friday
                desiredReplicas: 1
        - environment: test-large
          replicas: 0
          variables:
            ONESEISMIC_API_PORT: "8080"
            ONESEISMIC_API_CACHE_SIZE: "0" # MB
            ONESEISMIC_API_METRICS: "false"
            ONESEISMIC_API_METRICS_PORT: "8081"
            ONESEISMIC_API_TRUSTED_PROXIES: ""
            ONESEISMIC_API_BLOCKED_IPS: ""
            ONESEISMIC_API_BLOCKED_USER_AGENTS: ""
            OPENVDS_AZURE_IOMANAGER_THREAD_COUNT: ""
          secretRefs:
            azureKeyVaults:
              - name: S067-RadixKeyvault
                useAzureIdentity: true
                items:
                  - name: test-allowlist
                    envVar: ONESEISMIC_API_STORAGE_ACCOUNTS
          monitoring: true
          resources:
            requests:
              memory: "8192Mi"
              cpu: "2000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
