# yaml-language-server: $schema=https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json

apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oneseismictest
spec:
  environments:
    - name: test
      build:
        from: radix_playground
  components:
    - name: server
      dockerfileName: Dockerfile
      ports:
        - name: http
          port: 8080
        - name: metrics
          port: 8081
      publicPort: http
      monitoringConfig:
        portName: metrics
      identity:
        azure:
          clientId: fd162526-89a0-448a-979f-655c0717db52
      environmentConfig:
        - environment: test
          variables:
            ONESEISMIC_API_PORT: "8080"
            ONESEISMIC_API_CACHE_SIZE: "0" # MB
            ONESEISMIC_API_METRICS: "true"
            ONESEISMIC_API_METRICS_PORT: "8081"
            ONESEISMIC_API_TRUSTED_PROXIES: ""
            ONESEISMIC_API_BLOCKED_IPS: ""
            ONESEISMIC_API_BLOCKED_USER_AGENTS: ""
          secretRefs:
            azureKeyVaults:
              - name: S067-RadixKeyvault
                useAzureIdentity: true
                items:
                  - name: playground-test-allowlist
                    envVar: ONESEISMIC_API_STORAGE_ACCOUNTS
          monitoring: true
          resources:
            requests:
              memory: "500Mi"
              cpu: "200m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
