apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oneseismictest
spec:
  environments:
    - name: dev
      build:
        from: radix
    - name: test
      build:
        from: test
    - name: grpc
      build:
        from: grpc
  components:
    - name: server
      dockerfileName: Dockerfile
      ports:
        - name: http
          port: 8080
        - name: metrics
          port: 8081
      publicPort: http
      monitoringConfig:
        portName: metrics
      identity:
        azure:
          clientId: fd162526-89a0-448a-979f-655c0717db52
      environmentConfig:
        - environment: dev
          variables:
            VDSSLICE_PORT: 8080
            VDSSLICE_CACHE_SIZE: 512 # MB
            VDSSLICE_METRICS: true
            VDSSLICE_METRICS_PORT: 8081
          secretRefs:
            azureKeyVaults:
              - name: S067-RadixKeyvault
                useAzureIdentity: true
                items:
                  - name: playground-dev-allowlist
                    envVar: VDSSLICE_STORAGE_ACCOUNTS
          monitoring: true
          resources:
            requests:
              memory: "6144Mi"
              cpu: "4000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 3
        - environment: test
          variables:
            VDSSLICE_PORT: 8080
            VDSSLICE_CACHE_SIZE: 256 # MB
            VDSSLICE_METRICS: true
            VDSSLICE_METRICS_PORT: 8081
          secretRefs:
            azureKeyVaults:
              - name: S067-RadixKeyvault
                useAzureIdentity: true
                items:
                  - name: playground-test-allowlist
                    envVar: VDSSLICE_STORAGE_ACCOUNTS
          monitoring: true
          resources:
            requests:
              memory: "6144Mi"
              cpu: "2000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 3
        - environment: grpc
          enabled: false

    - name: scheduler
      dockerfileName: Dockerfile.scheduler
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: grpc
          variables:
            VDSSLICE_PORT: 8080
            VDSSLICE_CACHE_SIZE: 0 # MB
            VDSSLICE_JOBS: 64
            VDSSLICE_WORKER_ADDRESSES: "worker1:8090,worker2:8090,worker3:8090,worker4:8090"
            VDSSLICE_STORAGE_ACCOUNTS: "https://vdsbenchmark.blob.core.windows.net"
          resources:
            requests:
              memory: "6144Mi"
              cpu: "3000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
        - environment: dev
          enabled: false
        - environment: test
          enabled: false
    
    - name: worker1
      dockerfileName: Dockerfile.worker
      ports:
        - name: http 
          port: 8090
      environmentConfig:
        - environment: grpc
          variables:
            VDSSLICE_WORKER_PORTS: ":8090"
          resources:
            requests:
              memory: "6144Mi"
              cpu: "6000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
        - environment: dev
          enabled: false
        - environment: test
          enabled: false
    
    - name: worker2
      dockerfileName: Dockerfile.worker
      ports:
        - name: http 
          port: 8090
      environmentConfig:
        - environment: grpc
          variables:
            VDSSLICE_WORKER_PORTS: ":8090"
          resources:
            requests:
              memory: "6144Mi"
              cpu: "6000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
        - environment: dev
          enabled: false
        - environment: test
          enabled: false
    
    - name: worker3
      dockerfileName: Dockerfile.worker
      ports:
        - name: http 
          port: 8090
      environmentConfig:
        - environment: grpc
          variables:
            VDSSLICE_WORKER_PORTS: ":8090"
          resources:
            requests:
              memory: "6144Mi"
              cpu: "6000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
        - environment: dev
          enabled: false
        - environment: test
          enabled: false
    
    - name: worker4
      dockerfileName: Dockerfile.worker
      ports:
        - name: http 
          port: 8090
      environmentConfig:
        - environment: grpc
          variables:
            VDSSLICE_WORKER_PORTS: ":8090"
          resources:
            requests:
              memory: "6144Mi"
              cpu: "6000m"
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 1
        - environment: dev
          enabled: false
        - environment: test
          enabled: false
